### ISSUE TITLE
Invalid login attemp

### ISSUE THREAD

**Issue by Vova2805** [Vova2805/ScreenTaker#25]
Якщо ввести логін і пароль із пальця то викине на помилку
![default](https://cloud.githubusercontent.com/assets/11577478/15802090/5f2e64bc-2aa8-11e6-8018-ab61aaf551fa.PNG)

**Comment by dyvak** [comment]
Що треба зробити, щоб отримати цю помилку? В мене норм.
![image](https://cloud.githubusercontent.com/assets/17632584/15803198/8ed67a7e-2ada-11e6-8bc0-8182e9b4faed.png)
