### ISSUE TITLE
bugs list

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#78]
скрін 1.. футер підїхав вверх там біла смуга видна(форгот пассворд)
скрін 4 мініатюра вилізла за лінію разом з текстом (бібліотека картинок)
скрін 5.. кнопка  сабміт знаходиться під футером.. сама панель вверху образіється занадто низько(не під хедером)
скрін 6.. під боковоюю панеллю виникає "дира" якшо посувати нею вверх-вниз
скрін 7-8.. менедж аксес пперекривається футером і він скривається не під хедером а раніше(показано на прикладі шейр ссилки, яка образана не біля хедеру)
ост скрін .. те ж що і на 1 (форма логін)
![screenshot_2016-06-11-23-42-20](https://cloud.githubusercontent.com/assets/12258404/15987438/7abc3aea-3031-11e6-805c-2616838ccf3e.png)
![screenshot_2016-06-11-23-52-49](https://cloud.githubusercontent.com/assets/12258404/15987440/7ad40e18-3031-11e6-8e80-c4b1d40599b5.png)
![screenshot_2016-06-11-23-52-59](https://cloud.githubusercontent.com/assets/12258404/15987441/7ad5c046-3031-11e6-85ba-9f64f276e1d5.png)
![screenshot_2016-06-11-23-54-40](https://cloud.githubusercontent.com/assets/12258404/15987442/7adc422c-3031-11e6-9160-ca207ecfaffb.png)
![screenshot_2016-06-11-23-55-11](https://cloud.githubusercontent.com/assets/12258404/15987445/7aedef9a-3031-11e6-8df1-533088830ca9.png)
![screenshot_2016-06-11-23-55-53](https://cloud.githubusercontent.com/assets/12258404/15987444/7aed5012-3031-11e6-885b-bb7d0a02aa3c.png)
![screenshot_2016-06-11-23-56-12](https://cloud.githubusercontent.com/assets/12258404/15987443/7aed148a-3031-11e6-98be-b59ddd0a4d3e.png)
![screenshot_2016-06-11-23-41-54](https://cloud.githubusercontent.com/assets/12258404/15987446/7af10b58-3031-11e6-8b3f-d86573d67916.png)

**Comment by Vova2805** [comment]
скрін 2.. коли натиснути на локалізацію вискакує список..якшо нажати ще раз появляється то шо на скріні логоут і логін зникає і менюшка стає біла done

**Comment by Vova2805** [comment]
скірн 3.. не відображається мініатюра в панелі(сінглімейдж) done
