### ISSUE TITLE
Список багів розмітки 

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#84]
https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=http%3A%2F%2Fscreentaker.azurewebsites.net%2F#l6c28

**Comment by dimka14101** [comment]
це для http://screentaker.azurewebsites.net/
але і для http://screentakersigma2016.azurewebsites.net/ помилки актуальні

**Comment by Vova2805** [comment]
Це тільки для welcome)

**Comment by Vova2805** [comment]
Це вже краса коду. Нам треба щоб все пахало. Цим займемся пізніше
