### ISSUE TITLE
трабли розмітки ..по скрінах видно

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#85]
![capture](https://cloud.githubusercontent.com/assets/12258404/15991668/931c5b24-30c2-11e6-9c37-9da154518fd3.PNG)
![1](https://cloud.githubusercontent.com/assets/12258404/15991669/93215ef8-30c2-11e6-9090-d9f2c2ac0190.PNG)
![2](https://cloud.githubusercontent.com/assets/12258404/15991671/93219c92-30c2-11e6-86c4-afc619335fff.PNG)
![3](https://cloud.githubusercontent.com/assets/12258404/15991672/93225e66-30c2-11e6-849e-6e1c77c29163.PNG)
![4](https://cloud.githubusercontent.com/assets/12258404/15991670/93218c7a-30c2-11e6-84b1-739d8cb910a5.PNG)

**Comment by Vova2805** [comment]
Перероблено під різні розширення
