### ISSUE TITLE
Ексепшн при логінізації

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#88]
якщо в паролі понатискати кучу раз ентер (юзер пробував залогнитись по натиску ентера а не кнопки) то вискакує ексепшн..П.С. так не  кожного разу
![image](https://cloud.githubusercontent.com/assets/12258404/16036577/38740082-3225-11e6-99ad-6fbafb8ddf14.png)

**Comment by Vova2805** [comment]
Поставлю event на Enter як натиск на кнопку Login
