### ISSUE TITLE
Трабл розмітки

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#89]
при зміні розміру вікна панель збільшується перекриваючи кнопки, текст з кнопок вилазить , футер скаче вниз
![image](https://cloud.githubusercontent.com/assets/12258404/16036622/7e77d8ec-3225-11e6-9149-7852c5c0c0c9.png)

**Comment by Vova2805** [comment]
покажи мені то вживу бо в мене норм
