### ISSUE TITLE
Бібліотека, проблема панелі

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#90]
при запуску сторінки панель висовується задалеко, а хедер не примагнічений до країв(текст поїхав в центр) (скрін1)
після оновлення сторінки, панель робиться маленька , проблема з хедером залишається(скрін2)
Додаткова інф.: Тестування проходило на екрані 23'' 
Ймовірна причина: панель відкривається в процентному відношенні екрану, а кнопка регулюється відступом в пікселях відповідно на більшому екрані панель поїхала дальше а кнопка залишилась під нею 
![image](https://cloud.githubusercontent.com/assets/12258404/16036697/bb32aadc-3225-11e6-8368-fd069429d184.png)
![image](https://cloud.githubusercontent.com/assets/12258404/16036707/c994c83a-3225-11e6-95c6-a9d0ea1d15d0.png)

**Comment by Vova2805** [comment]
Done
