### ISSUE TITLE
Верхня панель і скролінг

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#91]
якшо відкрити панель і скролити, вона не ховається автоматично, футер щез, інколи появляється якшо порозширювати екран, появився скролл на панелі верхній..хз чого ... проблема з аватаром
![image](https://cloud.githubusercontent.com/assets/12258404/16036878/87b0280a-3226-11e6-9444-eef89b60e235.png)

**Comment by Vova2805** [comment]
Я перевірю
