### ISSUE TITLE
Підсвітка входу

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#95]
на формі входу при введені невірного паролю більше 5 символів поле стає зеленим, не знаю яку функцію воно має виконувати 
то саме в полі почти.. підсвітка стає зелена коли виконуються всі умови написання поштової адреси( англ букви, @ і крапка після неї і 2 символа після крапки) 
якшо так планувалось то все ок...якшо ж воно мало підсвічувати червоним те що не співадає з даними юзера для входу тоді це баг

**Comment by Vova2805** [comment]
так має бути. це фронтенд. тут перевіряється тільки валідність. нам не відомо чи він зареєстрований взагалі
