### ISSUE TITLE
знак > перетворюється

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#96]
знак > перетворбється.. на скріні видно... якшо на натиснути на фото то все ок... якшо оновити сторінку то то повторюється
![image](https://cloud.githubusercontent.com/assets/12258404/16082653/dec28184-331a-11e6-8128-627eaa45aef1.png)

**Comment by Vova2805** [comment]
Це тільки для першої так. Я вручну в js їх перетворю. Подібна проблема є в іншому issue
