### ISSUE TITLE
неможу перейменувати

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#97]
не відомо яка максимальна кількість символів, і нічо не виводить якшо ввести 20 символів.. і не перейменовує
![image](https://cloud.githubusercontent.com/assets/12258404/16082775/5ed3e340-331b-11e6-8e78-aa7eea04423b.png)

**Comment by dimka14101** [comment]
працює якшо 13 символів максимум ввести .. і то методом тику..ніяких попереджень нема

**Comment by Vova2805** [comment]
там все рівно скільки. в нас назва ховається а не обрізається
