### ISSUE TITLE
ПОмилка розмітки і ще кодування символів

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#98]
деякі символи все ще кодуються по іншому
кнопка внизу (обведена червоним) працює лише якшо нажати в червоній зоні
в інших місцях нічо не робиться
![image](https://cloud.githubusercontent.com/assets/12258404/16082974/ff08ec98-331b-11e6-9f89-61528e6fd6ef.png)

**Comment by dimka14101** [comment]
така штука робиться коли зображення з такими символами перше в списку.. якшо інше в списку то при натиску по ньому з назвами все ок

**Comment by Vova2805** [comment]
ясн. бо то треба вручну то обернути

**Comment by Vova2805** [comment]
<img width="1189" alt="screen shot 2016-06-15 at 9 49 16 pm" src="https://cloud.githubusercontent.com/assets/11577478/16093057/0c64d7fe-3343-11e6-8870-3a4af19ac837.png">
