### ISSUE TITLE
скочила смуга прокрутки 

### ISSUE THREAD

**Issue by dimka14101** [Vova2805/ScreenTaker#99]
![image](https://cloud.githubusercontent.com/assets/12258404/16083059/52ab228a-331c-11e6-8d5a-57746b228794.png)

**Comment by dimka14101** [comment]
то саме в single image і в folders

**Comment by Vova2805** [comment]
Це коли ти по вертикалі зменшуєш?

**Comment by Vova2805** [comment]
<img width="1177" alt="screen shot 2016-06-15 at 9 45 12 pm" src="https://cloud.githubusercontent.com/assets/11577478/16092937/7b41969a-3342-11e6-88e7-e0834821d724.png">
